# Generated by Django 3.1 on 2020-08-27 02:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200827_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanalysispage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('music_highlights', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=50)), ('url', wagtail.core.blocks.URLBlock(required=False))]), template='blocks/music_highlights.html')), ('learnings', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(), template='blocks/learnings.html')), ('stats', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.CharBlock(max_length=50)), ('description', wagtail.core.blocks.RichTextBlock())]), template='blocks/stats.html'))]),
        ),
    ]
