# Generated by Django 3.1 on 2020-08-28 01:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200827_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysislearning',
            name='page',
        ),
        migrations.RemoveField(
            model_name='analysismemorablemoment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='analysismusichighlight',
            name='page',
        ),
        migrations.AlterField(
            model_name='gameanalysispage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('music_highlights', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=50)), ('url', wagtail.core.blocks.URLBlock(required=False))]), template='blocks/music_highlights.html')), ('gameplay_mechanics', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(), icon='cogs', template='blocks/resume_skills.html')), ('learnings', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(), icon='tick', template='blocks/learnings.html')), ('memorable_moments', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(), icon='pick', template='blocks/memorable_moments.html')), ('stats', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.CharBlock(max_length=50)), ('description', wagtail.core.blocks.RichTextBlock())]), template='blocks/stats.html'))]),
        ),
        migrations.DeleteModel(
            name='AnalysisGameplayMechanic',
        ),
        migrations.DeleteModel(
            name='AnalysisLearning',
        ),
        migrations.DeleteModel(
            name='AnalysisMemorableMoment',
        ),
        migrations.DeleteModel(
            name='AnalysisMusicHighlight',
        ),
    ]
