# Generated by Django 3.1 on 2020-09-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('blog', '0011_auto_20200901_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameanalysispage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='gameanalysispage',
            name='translatablepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.translatablepage'),
            preserve_default=False,
        ),
    ]
