# Generated by Django 3.1 on 2020-09-07 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailtrans', '0009_create_initial_language'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0013_auto_20200902_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='DevJournalPage',
        ),
    ]
