# Generated by Django 3.1 on 2020-09-07 17:14

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200907_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='devjournalpage',
            name='post_index',
            field=models.IntegerField(default=1, verbose_name='Post index'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devjournalpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(template='blocks/paragraph.html'))]),
        ),
    ]
