# Generated by Django 3.1 on 2020-09-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('blog', '0015_auto_20200907_1414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devjournalpage',
            unique_together={('post_index', 'translatablepage_ptr_id')},
        ),
    ]
