# Generated by Django 3.1 on 2020-09-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('blog', '0016_auto_20200907_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devjournalpage',
            old_name='post_index',
            new_name='entry_index',
        ),
        migrations.AlterUniqueTogether(
            name='devjournalpage',
            unique_together={('entry_index', 'translatablepage_ptr_id')},
        ),
    ]
