# Generated by Django 3.1 on 2020-09-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200907_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devjournalpage',
            name='entry_index',
            field=models.IntegerField(verbose_name='Entry index'),
        ),
    ]
