# Generated by Django 3.1 on 2020-09-07 17:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200907_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devjournalpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(template='blocks/paragraph.html'))]),
        ),
    ]
