# Generated by Django 3.1 on 2020-09-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_category_commonpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
