# Generated by Django 3.1 on 2022-09-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gamepage_portfoliopage_resumepage_techused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='body',
        ),
    ]
