# Generated by Django 3.1 on 2022-09-23 02:44

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_portfoliopage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechUsed',
            new_name='Technology',
        ),
        migrations.RemoveField(
            model_name='gamepage',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='gamepage',
            name='start_year',
        ),
        migrations.AddField(
            model_name='gamepage',
            name='development_period',
            field=models.CharField(default=None, max_length=30, verbose_name='Development Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamepage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(template='blocks/paragraph.html')), ('award', wagtail.core.blocks.RichTextBlock(template='blocks/paragraph.html')), ('problem', wagtail.core.blocks.RichTextBlock(template='blocks/paragraph.html'))]),
        ),
    ]
