# Generated by Django 3.1 on 2022-09-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220922_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.gamepage')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.technology')),
            ],
        ),
    ]
