# Generated by Django 3.1 on 2022-09-23 04:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('home', '0008_gametechnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.Technology', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='technology',
            name='content_object',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tech_tags', to='home.gamepage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_technology_items', to='taggit.tag'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='technology',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='GameTechnology',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name',
        ),
    ]
