# Generated by Django 3.1 on 2022-09-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220923_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='itch_link',
            field=models.URLField(default='', verbose_name='itch.io URL'),
            preserve_default=False,
        ),
    ]
