# Generated by Django 3.1 on 2022-09-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_gamepage_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamepage',
            old_name='itch_link',
            new_name='itch_url',
        ),
        migrations.AddField(
            model_name='gamepage',
            name='youtube_url',
            field=models.URLField(default='', verbose_name='Youtube URL'),
            preserve_default=False,
        ),
    ]
