# Generated by Django 3.1 on 2022-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220927_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepage',
            name='itch_url',
            field=models.URLField(blank=True, verbose_name='itch.io URL'),
        ),
        migrations.AlterField(
            model_name='gamepage',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Youtube URL'),
        ),
    ]
