# Generated by Django 3.1 on 2022-09-27 14:57

from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220927_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock('image'))], default=None),
            preserve_default=False,
        ),
    ]
