# Generated by Django 3.1 on 2022-09-27 16:12

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_gamepage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumepage',
            name='location',
            field=models.CharField(default='', max_length=30, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumepage',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumepage',
            name='objective',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=wagtail.core.fields.StreamField([('skill_groups', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('group_description', wagtail.core.blocks.CharBlock(max_length=30)), ('skills', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(max_length=30)))]), template='blocks/resume_skills.html')), ('experience', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title_company', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('job_title', wagtail.core.blocks.CharBlock(max_length=50)), ('attributions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock()))]), template='blocks/resume_experience.html')), ('education', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('degree', wagtail.core.blocks.CharBlock(max_length=50))]), template='blocks/resume_education.html')), ('side_projects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('description', wagtail.core.blocks.RichTextBlock())]), template='blocks/resume_side_projects.html'))]),
        ),
    ]
