# Generated by Django 3.1 on 2022-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220927_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
