# Generated by Django 3.1 on 2022-09-27 16:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220927_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=wagtail.core.fields.StreamField([('skill_groups', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('group_description', wagtail.core.blocks.CharBlock(max_length=30))]), template='blocks/resume_skills.html')), ('experience', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title_company', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('job_title', wagtail.core.blocks.CharBlock(max_length=50))]), template='blocks/resume_experience.html')), ('education', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('degree', wagtail.core.blocks.CharBlock(max_length=50))]), template='blocks/resume_education.html')), ('side_projects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('description', wagtail.core.blocks.RichTextBlock())]), template='blocks/resume_side_projects.html'))]),
        ),
    ]
