# Generated by Django 3.1 on 2022-09-27 17:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220927_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='education',
            field=wagtail.core.fields.StreamField([('education', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('degree', wagtail.core.blocks.CharBlock(max_length=50))]), template='blocks/resume_education.html'))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumepage',
            name='experience',
            field=wagtail.core.fields.StreamField([('experience', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title_company', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('job_title', wagtail.core.blocks.CharBlock(max_length=50)), ('attributions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock()))]), template='blocks/resume_experience.html'))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumepage',
            name='side_projects',
            field=wagtail.core.fields.StreamField([('side_projects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=30)), ('period', wagtail.core.blocks.CharBlock(max_length=30)), ('description', wagtail.core.blocks.RichTextBlock())]), template='blocks/resume_side_projects.html'))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumepage',
            name='skills',
            field=wagtail.core.fields.StreamField([('skill_group', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('group_description', wagtail.core.blocks.CharBlock(max_length=30)), ('skill', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(max_length=30)))]), template='blocks/resume_skills.html'))], default=''),
            preserve_default=False,
        ),
    ]
