# Generated by Django 3.1 on 2022-09-27 17:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220927_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='skills',
            field=wagtail.core.fields.StreamField([('skill_group', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('group_description', wagtail.core.blocks.CharBlock(max_length=30)), ('skills', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(max_length=30)))]), template='blocks/resume_skills.html'))]),
        ),
    ]
