# Generated by Django 3.1 on 2022-09-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0023_auto_20220927_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepage',
            name='body',
        ),
        migrations.AddField(
            model_name='resumepage',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
