# Generated by Django 3.1 on 2022-09-29 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220927_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='development_end',
            field=models.DateField(blank=True, null=True, verbose_name='Development End'),
        ),
        migrations.AddField(
            model_name='gamepage',
            name='development_start',
            field=models.DateField(default=datetime.date(2022, 9, 29), verbose_name='Development Start'),
            preserve_default=False,
        ),
    ]
