# Generated by Django 3.1 on 2022-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220929_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepage',
            name='development_end',
        ),
        migrations.RemoveField(
            model_name='gamepage',
            name='development_start',
        ),
        migrations.AddField(
            model_name='gamepage',
            name='dev_end_month',
            field=models.SmallIntegerField(default=0, verbose_name='Development End Year'),
        ),
        migrations.AddField(
            model_name='gamepage',
            name='dev_start_month',
            field=models.SmallIntegerField(default=0, verbose_name='Development Start Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamepage',
            name='dev_start_year',
            field=models.SmallIntegerField(default=0, verbose_name='Development Start Year'),
            preserve_default=False,
        ),
    ]
