# Generated by Django 3.1 on 2022-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220929_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='dev_end_year',
            field=models.SmallIntegerField(default=0, verbose_name='Development End Year'),
        ),
        migrations.AlterField(
            model_name='gamepage',
            name='dev_end_month',
            field=models.SmallIntegerField(default=0, verbose_name='Development End Month'),
        ),
    ]
