# Generated by Django 3.1 on 2022-09-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20220929_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepage',
            name='development_period',
        ),
    ]
